name: reusable-ci
on:
  workflow_call:
    inputs:
      service:
        required: false
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node + cache configured for BOTH pnpm and npm
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # If you later add pnpm-lock.yaml, caching will work automatically
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install pnpm
        run: npm install -g pnpm@9

      # ---- Dependency install matrix (no lockfile? still install) ----
      # 1) If pnpm lockfile exists, do a strict install (fast & reproducible)
      - name: Install deps with pnpm (locked)
        if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
        run: pnpm install --frozen-lockfile

      # 2) Else if npm lockfile exists, use npm ci
      - name: Install deps with npm ci
        if: ${{ hashFiles('**/package-lock.json') != '' || hashFiles('**/npm-shrinkwrap.json') != '' }}
        run: npm ci

      # 3) Else no lockfile at all – just install so the build can proceed
      - name: Install deps (no lockfile present)
        if: ${{ hashFiles('**/pnpm-lock.yaml') == '' && hashFiles('**/package-lock.json') == '' && hashFiles('**/npm-shrinkwrap.json') == '' && hashFiles('**/yarn.lock') == '' }}
        run: |
          echo "No lockfile found. Installing with pnpm (non-frozen)."
          pnpm install

      # Lint/Typecheck/Tests are best-effort so a missing script doesn’t fail CI early
      - name: Lint & Typecheck (best-effort)
        run: |
          pnpm -w run lint || echo "lint skipped"
          pnpm -w run typecheck || echo "typecheck skipped"

      - name: Unit tests (best-effort)
        run: pnpm -w run test -- --coverage || echo "tests skipped"

      # Build & push container images for changed services (to GHCR)
      - name: Build Docker images for changed services
        env:
          REGISTRY: ghcr.io/${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # for GHCR login
        run: bash scripts/build_and_push_images.sh

      - name: Container scan with Trivy (non-blocking)
        run: bash scripts/scan_images.sh || echo "scan warnings (not failing build)"
