name: reusable-ci

on:
  workflow_call:
    inputs:
      service:
        required: false
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      # ✅ Robust pnpm install (adds pnpm to PATH consistently)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Print tool versions
        run: |
          node -v
          npm -v
          pnpm -v

      # ---- Dependency install logic (monorepo-safe, no silent skips) ----
      # Prefer pnpm if a pnpm lock exists anywhere
      - name: Install deps with pnpm (frozen if lock exists)
        run: |
          if [ -n "$(git ls-files '**/pnpm-lock.yaml')" ]; then
            echo "Found pnpm-lock.yaml → running pnpm install --frozen-lockfile (workspace-aware if present)"
            pnpm install --frozen-lockfile
          elif [ -n "$(git ls-files '**/package-lock.json' '**/npm-shrinkwrap.json')" ]; then
            echo "Found npm lockfile → running npm ci at repo root"
            npm ci || true
          else
            echo "No lockfile found → running pnpm install (non-frozen) to proceed"
            pnpm install || true
          fi

      # Best-effort static checks (won’t fail if scripts don’t exist yet)
      - name: Lint & Typecheck (best-effort)
        run: |
          pnpm -w run lint || echo "lint skipped"
          pnpm -w run typecheck || echo "typecheck skipped"

      - name: Unit tests (best-effort)
        run: pnpm -w run test -- --coverage || echo "tests skipped"

      # Build & push container images for changed services (to GHCR)
      - name: Build Docker images for changed services
        env:
          REGISTRY: ghcr.io/${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # needed for GHCR login
        run: bash scripts/build_and_push_images.sh

      - name: Container scan with Trivy (non-blocking)
        run: bash scripts/scan_images.sh || echo "scan warnings (not failing build)"
