name: reusable-ci
on:
  workflow_call:
    inputs:
      service:
        required: false
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node first
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Cache for pnpm if/when a pnpm-lock.yaml exists
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      # ✅ Always install pnpm BEFORE any pnpm command runs
      - name: Install pnpm
        run: npm install -g pnpm@9

      # ---- Dependency install logic (works with or without lockfiles) ----
      # If pnpm lockfile exists anywhere (monorepo-safe) → strict install
      - name: Install deps with pnpm (locked)
        if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
        run: pnpm install --frozen-lockfile

      # If npm lockfile exists instead → npm ci
      - name: Install deps with npm ci
        if: ${{ hashFiles('**/pnpm-lock.yaml') == '' && (hashFiles('**/package-lock.json') != '' || hashFiles('**/npm-shrinkwrap.json') != '') }}
        run: npm ci

      # No lockfile at all → do a non-frozen install so CI can proceed
      - name: Install deps (no lockfile present)
        if: ${{ hashFiles('**/pnpm-lock.yaml') == '' && hashFiles('**/package-lock.json') == '' && hashFiles('**/npm-shrinkwrap.json') == '' && hashFiles('**/yarn.lock') == '' }}
        run: |
          echo "No lockfile found. Installing with pnpm (non-frozen)."
          pnpm install || true

      # Best-effort checks — won’t fail if scripts don’t exist yet
      - name: Lint & Typecheck (best-effort)
        run: |
          pnpm -w run lint || echo "lint skipped"
          pnpm -w run typecheck || echo "typecheck skipped"

      - name: Unit tests (best-effort)
        run: pnpm -w run test -- --coverage || echo "tests skipped"

      # Build & push container images for changed services (to GHCR)
      - name: Build Docker images for changed services
        env:
          REGISTRY: ghcr.io/${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # for GHCR login
        run: bash scripts/build_and_push_images.sh

      - name: Container scan with Trivy (non-blocking)
        run: bash scripts/scan_images.sh || echo "scan warnings (not failing build)"
