name: staging
on:
  push:
    branches: [ main ]

jobs:
  # Reuse your CI (lint/test/build/push images)
  ci:
    uses: ./.github/workflows/reusable-ci.yml

  # Deploy to staging after CI succeeds
  deploy-staging:
    needs: ci
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      # Ensure Node + pnpm exist IN THIS JOB
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure pnpm on PATH
        run: bash scripts/pnpm_ensure.sh

      - name: Check pnpm
        run: pnpm -v

      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run migrations (expand-safe)
        env:
          STAGING_DB_URL: ${{ secrets.STAGING_DB_URL }}
        run: bash scripts/migrate_expand.sh "$STAGING_DB_URL"

      - name: Deploy changed services to staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: bash scripts/deploy_changed_services.sh "staging" "staging"

      - name: Smoke tests
        run: bash scripts/smoke_tests.sh
